
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file: ".env.dev"
    depends_on:
      - db
    networks:
      - chat_network

  db:
    image: postgres:13.22-alpine3.22
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
    networks:
      - chat_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - chat_network

networks:
  chat_network:
