"""change size

Revision ID: 12ab75ca5f74
Revises: c21f4c761e28
Create Date: 2025-08-22 05:08:31.158541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '12ab75ca5f74'
down_revision: Union[str, None] = 'c21f4c761e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentindex', 'chunk_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentindex', 'chunk_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               existing_nullable=False)
    # ### end Alembic commands ###
