"""updated constraints

Revision ID: 6ab0ef41156f
Revises: 91d880609cd2
Create Date: 2025-08-23 02:51:09.314305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6ab0ef41156f'
down_revision: Union[str, None] = '91d880609cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatmessage_session_id_fkey', 'chatmessage', type_='foreignkey')
    op.create_foreign_key(None, 'chatmessage', 'chatsession', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint('documentindex_session_id_fkey', 'documentindex', type_='foreignkey')
    op.create_foreign_key(None, 'documentindex', 'chatsession', ['session_id'], ['session_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentindex', type_='foreignkey')
    op.create_foreign_key('documentindex_session_id_fkey', 'documentindex', 'chatsession', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'chatmessage', type_='foreignkey')
    op.create_foreign_key('chatmessage_session_id_fkey', 'chatmessage', 'chatsession', ['session_id'], ['session_id'])
    # ### end Alembic commands ###
