"""embedding tied to session

Revision ID: 7b335015f445
Revises: 086173993d43
Create Date: 2025-08-22 15:49:09.910662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '7b335015f445'
down_revision: Union[str, None] = '086173993d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentindex', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documentindex', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'documentindex', 'chatsession', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentindex', type_='foreignkey')
    op.drop_column('documentindex', 'updated_at')
    op.drop_column('documentindex', 'created_at')
    # ### end Alembic commands ###
