"""added timestamp columns

Revision ID: 7d4cd53ed497
Revises: 24daf5188ab8
Create Date: 2025-08-21 20:07:17.493696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d4cd53ed497'
down_revision: Union[str, None] = '24daf5188ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chatmessage', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('chatmessage', 'timestamp')
    op.add_column('chatsession', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chatsession', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatsession', 'updated_at')
    op.drop_column('chatsession', 'created_at')
    op.add_column('chatmessage', sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chatmessage', 'updated_at')
    op.drop_column('chatmessage', 'created_at')
    # ### end Alembic commands ###
