"""added session_id

Revision ID: af87cac9f1ee
Revises: 12ab75ca5f74
Create Date: 2025-08-22 06:52:31.806737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'af87cac9f1ee'
down_revision: Union[str, None] = '12ab75ca5f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentindex', sa.Column('session_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentindex', 'session_id')
    # ### end Alembic commands ###
