"""role column

Revision ID: d28141236d7a
Revises: 7d4cd53ed497
Create Date: 2025-08-21 20:53:35.148383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd28141236d7a'
down_revision: Union[str, None] = '7d4cd53ed497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'role')
    # ### end Alembic commands ###
