"""pgvector

Revision ID: dc16c2c218ef
Revises: d28141236d7a
Create Date: 2025-08-22 04:27:56.530267

"""
from typing import Sequence, Union
from sqlmodel import text
from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision: str = 'dc16c2c218ef'
down_revision: Union[str, None] = 'd28141236d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text('CREATE EXTENSION IF NOT EXISTS vector'))
    op.add_column('chatmessage', sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatmessage', sa.Column('embedding', VECTOR(dim=768), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'embedding')
    op.drop_column('chatmessage', 'context')
    op.execute(text('DROP EXTENSION vector'))
    # ### end Alembic commands ###
